const DummyData = [
  {
    id: 1,
    name: 'Laptop',
    category: 'Electronics',
    price: 800,
    rating: 3.5,
  },
  {
    id: 2,
    name: 'Smartphone',
    category: 'Electronics',
    price: 500,
    rating: 4.3,
  },
  {
    id: 3,
    name: 'Tablet',
    category: 'Electronics',
    price: 300,
    rating: 4.0,
  },
  {
    id: 4,
    name: 'Headphones',
    category: 'Accessories',
    price: 100,
    rating: 4.1,
  },
  {
    id: 5,
    name: 'Keyboard',
    category: 'Accessories',
    price: 50,
    rating: 3,
  },
  {
    id: 6,
    name: 'Mouse',
    category: 'Accessories',
    price: 30,
    rating: 4.0,
  },
  {
    id: 7,
    name: 'Smart Watch',
    category: 'Wearables',
    price: 200,
    rating: 4.4,
  },
  {
    id: 8,
    name: 'Fitness Tracker',
    category: 'Wearables',
    price: 120,
    rating: 4.3,
  },
  {
    id: 9,
    name: 'Monitor',
    category: 'Electronics',
    price: 250,
    rating: 4.6,
  },
  {
    id: 10,
    name: 'TV',
    category: 'Electronics',
    price: 1000,
    rating: 4.7,
  },
  {
    id: 11,
    name: 'Refrigerator',
    category: 'Home Appliances',
    price: 700,
    rating: 4.8,
  },
  {
    id: 12,
    name: 'Washing Machine',
    category: 'Home Appliances',
    price: 600,
    rating: 3.2,
  },
  {
    id: 13,
    name: 'Microwave',
    category: 'Home Appliances',
    price: 150,
    rating: 3.4,
  },
  {
    id: 14,
    name: 'Blender',
    category: 'Kitchen',
    price: 80,
    rating: 4.2,
  },
  {
    id: 15,
    name: 'Coffee Maker',
    category: 'Kitchen',
    price: 90,
    rating: 4.3,
  },
  {
    id: 16,
    name: 'Dishwasher',
    category: 'Home Appliances',
    price: 550,
    rating: 3.5,
  },
  {
    id: 17,
    name: 'Vacuum Cleaner',
    category: 'Home Appliances',
    price: 300,
    rating: 3,
  },
  {
    id: 18,
    name: 'Air Purifier',
    category: 'Home Appliances',
    price: 200,
    rating: 4.5,
  },
  {
    id: 19,
    name: 'Water Purifier',
    category: 'Home Appliances',
    price: 180,
    rating: 4.4,
  },
  {
    id: 20,
    name: 'Electric Kettle',
    category: 'Kitchen',
    price: 40,
    rating: 4.1,
  },
  {
    id: 21,
    name: 'Oven',
    category: 'Kitchen',
    price: 250,
    rating: 4,
  },
  {
    id: 22,
    name: 'Sofa',
    category: 'Furniture',
    price: 1200,
    rating: 4.8,
  },
  {
    id: 23,
    name: 'Dining Table',
    category: 'Furniture',
    price: 1000,
    rating: 4.7,
  },
  {
    id: 24,
    name: 'Bed Frame',
    category: 'Furniture',
    price: 900,
    rating: 4.6,
  },
  {
    id: 25,
    name: 'Wardrobe',
    category: 'Furniture',
    price: 800,
    rating: 4.5,
  },
  {
    id: 26,
    name: 'Chair',
    category: 'Furniture',
    price: 100,
    rating: 4.2,
  },
  {
    id: 27,
    name: 'Desk',
    category: 'Furniture',
    price: 200,
    rating: 4.3,
  },
  {
    id: 28,
    name: 'Bookshelf',
    category: 'Furniture',
    price: 300,
    rating: 4.4,
  },
  {
    id: 29,
    name: 'Curtains',
    category: 'Home Decor',
    price: 50,
    rating: 4.0,
  },
  {
    id: 30,
    name: 'Wall Art',
    category: 'Home Decor',
    price: 70,
    rating: 4.3,
  },
];

export default DummyData;
